### PR TITLE
V10X-HACK-YEMEN1

### PR DESCRIPTION
**Pull request by SAMIV10X**
هذي الاداة اختراق جميع موقع التواصل الاجتماعي

$ apt update -y

$ apt upgrade -y

$ apt install git

$ git clone https://github.com/Cesar-Hack-Gray/SocialSploit

$ cd SocialSploit

$ bash install.sh

$ ./Sploit

### CODE REVIEW

**Comment by SAMIV10X** [comment]
#!/bin/babashW='\033[90m'G='\033[1;36m'WW='\033[32m'home=`pwd`guillon="-y"Cesar1="@CesarHackGray"link="https://t.me/CesarGray"Usage="./Sploit [disfruta]"Gray1="curl"Gray2="php"Gray3="openssh"Gray4="python2"Gray5="wget"Gray6="python"Home2="bash"if [ -e /data/data/com.termux/files/usr/bin ]; then	Cesar="pkg"else	Cesar="sudo apt-get"fibash ${home}/Eticalrm -rf ${home}/Eticalecho -e ${G}"[+]${W} Instalando ${Gray1}..."${Cesar} Install ${guillon} ${Gray1} &amp;&gt;&gt; /dev/nullecho -e ${G}"[+]${W} Instalando ${Gray2}..."${Cesar} install ${guillon} ${Gray2} &amp;&gt;&gt; /dev/nullecho -e ${G}"[+]${W} Instalando ${Gray3}..."${Cesar} install ${guillon} ${Gray3} &amp;&gt;&gt; /dev/nullecho -e ${G}"[+]${W} Instalando ${Gray4}..."${Cesar} install ${guillon} ${Gray4} &amp;&gt;&gt; /dev/nullecho -e ${G}"[+]${W} Instalando ${Gray5}..."${Cesar} install ${guillon} ${Gray5} &amp;&gt;&gt; /dev/nullecho -e ${G}"[+]${W} Instalando ${Gray6}..."${Cesar} install ${guillon} ${Gray6} &amp;&gt;&gt; /dev/null
echoecho -e ${G}"[+]${W} Finished"echo -e ${G}"[+]${W} Created by ${Cesar1}..."echo -e ${G}"[+]${W} Contactame ${link}.."echo -e ${G}"[+]${W} Usage ${Usage}"echochmod +x ${home}/Sploitrm -rf ${home}/install.shexit

**Comment by SAMIV10X** [comment]
هذي الاداة اختراق جميع موقع التواصل الاجتماعي

$ apt update -y

$ apt upgrade -y

$ apt install git

$ git clone https://github.com/Cesar-Hack-Gray/SocialSploit

$ cd SocialSploit

$ bash install.sh

$ ./Sploit

**Comment by SAMIV10X** [comment]
68985817-f8693500-07de-11ea-8a64-592468ed1440 es.githubusercontent.com/85111528/120246699-b21cdf00-c279-11eb-980f-974e8420f80e.jpg)

**Comment by Cesar-Hack-Gray** [comment]
urime, nuk keni hakuar asgjë  🤣🤣🤣🤣🤣 xD

**Pull request closed without merging**
